name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Установка зависимостей
        run: npm install

      - name: Сборка проекта
        run: npm run build

      - name: Архивация сборки
        run: tar -czf next.tar.gz .next

      - name: Загрузка в artifacts
        uses: actions/upload-artifact@v4
        with:
          name: .next
          path: next.tar.gz

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Скачиваем artifact с архивом
        uses: actions/download-artifact@v4
        with:
          name: .next
          path: ./next-artifact

      - name: Подключаюсь к серверу
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Копирую архив на сервер
        run: |
          scp -o StrictHostKeyChecking=no ./next-artifact/next.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:~/projects/igor-edison-personal/

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd ~/projects/igor-edison-personal
            rm -rf .next/*
            tar -xzf next.tar.gz
            rm next.tar.gz
            rm -rf /var/www/igor-edison-personal.ru/*
            mv ~/projects/igor-edison-personal/.next/* /var/www/igor-edison-personal.ru
          port: 22
          protocol: tcp
          timeout: 30s
          command_timeout: 10m
          proxy_port: 22
          proxy_timeout: 30s
